-- Increase password column to store BCrypt hash (60 chars) with room to spare
ALTER TABLE users
    ALTER COLUMN password TYPE VARCHAR(255);

-- Store refresh tokens in DB for validation and revocation
CREATE TABLE IF NOT EXISTS refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    token      VARCHAR(512)                            NOT NULL,
    expires_at TIMESTAMP                               NOT NULL,
    revoked    BOOLEAN                                 NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP                               NOT NULL DEFAULT now(),
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uidx_refresh_tokens_token ON refresh_tokens (token);
